In [ ]:
#Nithin Thota
#700764916

In [2]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees += 1


    def averageSalary(employee_list):
        totalSalary = sum(employee.salary for employee in employee_list)
        return totalSalary / len(employee_list)


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


employee1 = Employee("Nithin", "Thota", 90000, "Manager")
employee2 = Employee("Srinivas", "Thota", 80000, "Finance")
employee3=  Employee("Nikhil",     "koti",    70000, "Digital Marketing")

fullTimeEmployee1 = FulltimeEmployee("pavan", "kumar",25000, "HR")
fullTimeEmployee2 = FulltimeEmployee("Moksha", "panala", 35000, "Lead")

employees = [employee1, employee2, fullTimeEmployee1, fullTimeEmployee2]

avgSalary = Employee.averageSalary(employees)
print("Average Salary For All the Full Time And Employees :", avgSalary)
print("Total Number of full time and Employees:", Employee.numberOfEmployees)

Average Salary For All the Full Time And Employees : 57500.0
Total Number of full time and Employees: 5


In [3]:
import numpy as np
randomVector = np.random.uniform(1, 20, 20)
reshapedArray = randomVector.reshape(4, 5)
reshapedArray[np.arange(reshapedArray.shape[0]), reshapedArray.argmax(axis=1)] = 0
print(reshapedArray)


[[11.08277065  6.18783098  2.77040365 10.51294246  0.        ]
 [ 5.6269184  10.00322096  0.          6.82182726  9.71143368]
 [ 0.          7.4737138   1.96202624  7.89112231 11.50135024]
 [11.80891135  0.         19.90806451  3.44846593 16.61160375]]
